server:
  port: 8090

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

feign:
  hystrix:
    enabled: true

customers:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8080